### ISSUE TITLE
Unhandled error whenever it tries to send the Player Count

### ISSUE THREAD

**Issue by ClintonButler** [robbyjm/RobbysPlayerPlugin#5]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "twisted\internet\base.pyo", line 1192, in run

  File "twisted\internet\base.pyo", line 1201, in mainLoop

  File "twisted\internet\base.pyo", line 824, in runUntilCurrent

  File "twisted\internet\task.pyo", line 218, in __call__

--- <exception caught here> ---
  File "twisted\internet\defer.pyo", line 139, in maybeDeferred

  File "C:\DayZServer\battleye\Plugins\RobbysPlayerPlugin\__init__.py", line 34, in send_player_count

exceptions.ValueError: zero length field name in format

**Comment by robbyjm** [comment]
@Wizbaggd thanks for reporting this. I pulled a request without testing it and there was python code from 2.7+ that's unsupported in 2.6. Try it now it should work

**Comment by ClintonButler** [comment]
Unfortunately even with a fresh grab did not work. Same error.
